# ********************************************
# HOW TO RUN JACOB CLOUSE'S CIPHER FOR HM1 526
# ********************************************


'''ENCRYPTION'''

# 1) Move this program into its own folder


# 2) Open either a GIT BASH terminal or BASH TERMINAL and navigate into the folder that contains the program


# 3) Run this program with the command: python jacob-final-cipher.py 
#       NOTE: if you have python2 and python3 installed use this command: python3 jacob-final-cipher.py


# 4) The first thing it will ask you for is if you want to either 'Encrypt' or 'Decrypt', type in 'Encrypt'


# 5) The next thing it will ask you for is the plaintext, enter in the message you want to encode


# 6) It should let you know that a simple subsitution cipher has been activated, then you have to enter in the offset you want to set
#       Any number between 1 and 26


# 7) It should move onto the transposition cipher, and will ask you for a unique sequence of the numbers: 1,2,3,4
